//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_WebForm_Prodject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Data.SqlClient;

    public partial class DeliverySlip
    {
        public string SlipID { get; set; }
        public string OrderID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> TotalBill { get; set; }
        public Nullable<bool> SlipDeleted { get; set; }
    
        public virtual C_Order C_Order { get; set; }

        public List<DeliverySlip> SelectDeliverySlipQuery()
        {
            List<DeliverySlip> res = new List<DeliverySlip>();
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                SqlCommand cmd = new SqlCommand("select * from DeliverySlip", conn);

                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    DeliverySlip deliverySlip = new DeliverySlip();
                    deliverySlip.SlipID = dr["SlipID"].ToString();
                    deliverySlip.OrderID = dr["OrderID"].ToString();
                    deliverySlip.DeliveryDate = Convert.ToDateTime(dr["DeliveryDate"]);
                    deliverySlip.TotalBill = Convert.ToDecimal(dr["TotalBill"]);
                    res.Add(deliverySlip);
                }
            }
            return res;
        }

        public void AddDeliverySlipQuery(
            string SlipID,
            string OrderID,
            DateTime DeliveryDate,
            decimal TotalBill)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string importDate = DeliveryDate.ToString("yyyy-MM-dd HH:mm:ss");
                string sql = "insert into DeliverySlip values ('" +
                    SlipID +
                    "', '" + OrderID +
                    "', '" + importDate +
                    "', " + TotalBill +
                    ", " + 0 + ")";
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.ExecuteNonQuery();
            }
        }

        public void UpdateDeliverySlipQuery(string SlipID, string attribute, string value)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "";
                if (attribute == "TotalBill")
                {
                    sql = "update DeliverySlip set" +
                    " TotalBill = " + Convert.ToDecimal(value) +
                    " where SlipID = '" + SlipID + "'";
                }
                else
                {
                    sql = "update DeliverySlip set" +
                    " " + attribute + " = '" + Convert.ToDecimal(value) +
                    "' where SlipID = '" + SlipID + "'";
                }
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.ExecuteNonQuery();
            }
        }

        private string GetDeliverySlipDesc()
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "select top 1 SlipID from DeliverySlip order by SlipID desc";
                SqlCommand cmd = new SqlCommand(sql, conn);

                SqlDataReader dr = cmd.ExecuteReader();
                string res = "";
                while (dr.Read())
                {
                    res = dr["SlipID"].ToString();
                }
                return res;
            }
        }

        public string GetNewDeliverySlipID()
        {
            string res = GetDeliverySlipDesc();
            if (res != null && !res.Equals(""))
            {
                int order = int.Parse(res.Substring(4)) + 1;
                if (order < 10)
                {
                    res = "DSMP00000" + order.ToString();
                }
                else if (order < 100)
                {
                    res = "DSMP0000" + order.ToString();
                }
                else if (order < 1000)
                {
                    res = "DSMP000" + order.ToString();
                }
                else if (order < 10000)
                {
                    res = "DSMP00" + order.ToString();
                }
                else if (order < 100000)
                {
                    res = "DSMP0" + order.ToString();
                }
                else
                {
                    res = "DSMP" + order.ToString();
                }
                return res;
            }
            else
            {
                return "DSMP000001";
            }
        }
    }
}
