//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_WebForm_Prodject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySlip
    {
        public string SlipID { get; set; }
        public string OrderID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> TotalBill { get; set; }
        public Nullable<bool> SlipDeleted { get; set; }
    
        public virtual C_Order C_Order { get; set; }
    }
}
