//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_WebForm_Prodject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouseReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WareHouseReceipt()
        {
            this.WareHouseReceiptDetails = new HashSet<WareHouseReceiptDetail>();
        }
    
        public string WarehouseReceiptID { get; set; }
        public string StaffID { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<decimal> WarehouseTotalBill { get; set; }
        public Nullable<bool> WarehouseDeleted { get; set; }
    
        public virtual C_User C_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WareHouseReceiptDetail> WareHouseReceiptDetails { get; set; }
    }
}
